name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Lint"
        uses: ./.github/workflows/lint.yml

      - name: "Validate"
        uses: ./.github/workflows/validate.yml

      - name: "Adjust version number"
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.ref_name }}"' \
            "${{ github.workspace }}/custom_components/myrfplayer/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/myrfplayer"
          zip myrfplayer.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ${{ github.workspace }}/custom_components/myrfplayer/myrfplayer.zip
